#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        22_create_group.yml 
# Author:       Adrian Bronder
# Date:         2020-06-25
# Description:  Create a group on tenant/org
#               with Ansible modules
#
# Modules:      nac_sg_org_group
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://galaxy.ansible.com/netapp/storagegrid
#
# Built-in help:
# ansible-doc netapp.storagegrid.nac_sg_org_group
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ grid_auth_response.json.data }}"
      validate_certs:          false
    input_tenant: &input_tenant
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ tenant_auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method: POST
      body: {
        "username":                "{{ SG_ADMIN_USER }}",
        "password":                "{{ SG_ADMIN_PASS }}",
        "cookie":                  false,
        "csrfToken":               false
      }
      body_format: json
      validate_certs: false
    register: grid_auth_response

  - name: Get GRID tenants
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/grid/accounts?includeMarker=true"
      method: GET
      headers: {
        "accept":                  "application/json",
        "Authorization":           "{{ grid_auth_response.json.data }}"
      }
      validate_certs: false
    register: grid_tenants

  - name: Get tenant by name
    set_fact:
      selected_tenant: '{{ grid_tenants.json.data |
                           selectattr("name", "equalto", TENANT) |
                           list }}'

  - name: Check for unique tenant
    fail:
      msg: "Unique tenant ID for given name '{{ TENANT }}' not found"
    when:
      ( selected_tenant | length ) != 1

  - name: Get tenant authorization token
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method: POST
      body: {
        "accountId":               "{{ selected_tenant.0.id }}",
        "username":                "root",
        "password":                "{{ TENANT_ROOT_PASS }}",
        "cookie":                  false,
        "csrfToken":               false
      }
      body_format: json
      validate_certs: false
    register: tenant_auth_response

  - name: Create group
    nac_sg_org_group:
      state:                       present
      display_name:                "{{ TENANT }}-{{ GROUP_NAME }}"
      unique_name:                 "group/{{ TENANT }}-{{ GROUP_NAME }}"
      management_policy:
        manage_all_containers:     true
        manage_endpoints:          true
        manage_own_s3_credentials: false
        root_access:               false
      s3_policy:
        Statement:
        - Effect: Allow
          Action: s3:*
          Resource: arn:aws:s3:::*
      <<: *input_tenant
