#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        91_delete_new_app.yml 
# Author:       Adrian Bronder
# Date:         2020-06-24
# Description:  Clean up entire environment
#               with Ansible modules
#
# Modules:      nac_sg_grid_account
#               nac_sg_org_container
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://galaxy.ansible.com/netapp/storagegrid
#
# Built-in help:
# ansible-doc netapp.storagegrid.nac_sg_org_container
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ grid_auth_response.json.data }}"
      validate_certs:          false
    input_tenant: &input_tenant
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ tenant_auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../new_app.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: grid_auth_response

  - name: Get Grid Tenants
    netapp.storagegrid.na_sg_grid_info:
      gather_subset: grid_accounts_info
      <<: *input_grid
    register: grid_tenants

  - name: Get tenant by name
    set_fact:
      selected_tenant: "{{ grid_tenants.sg_info['grid/accounts'].data |
                        selectattr('name', 'equalto', TENANT) |
                        list }}"

  - name: Check for unique tenant
    fail:
      msg: "Unique tenant ID for given name '{{ TENANT }}' not found"
    when:
      ( selected_tenant | length ) != 1

  - name: Get tenant authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "accountId":           "{{ selected_tenant.0.id }}",
        "username":            "root",
        "password":            "{{ TENANT_ROOT_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: tenant_auth_response

  - name: Check existence of S3 credentials
    stat:
      path:                    "../cred_store/{{ TENANT }}-{{ TENANT_USER_NAME }}"
    register: s3cred_file

  - name: Read S3 credentials
    set_fact:
      s3cred: "{{ lookup('file', '../cred_store/{{ TENANT }}-{{ TENANT_USER_NAME }}')}}"
    when:
      s3cred_file.stat.exists

  - name: Get Buckets for Tenant - {{ TENANT }}
    netapp.storagegrid.na_sg_org_info:
      gather_subset: org/containers
      <<: *input_tenant
    register: tenant_buckets

  - name: Delete S3 buckets
    s3_bucket:
      name:                    "{{ item.name }}"
      s3_url:                  "https://{{ SG_GW_NODE1 }}/"
      aws_access_key:          "{{ s3cred.accessKey }}"
      aws_secret_key:          "{{ s3cred.secretAccessKey }}"
      validate_certs:          false
      state:                   absent
    loop: "{{ tenant_buckets.sg_info['org/containers'].data }}"

  - name: Delete GRID tenant
    netapp.storagegrid.na_sg_grid_account:
      state:                   absent
      name:                    "{{ selected_tenant.0.name }}"
      protocol:                s3
      <<: *input_grid
