#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        01_get_cluster_details.yml
# Author:       Adrian Bronder
# Date:         2020-03-18
# Description:  Get cluster information
#               with Ansible modules
#
# Modules:      na_ontap_info
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_info
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Get Ontap Info
    na_ontap_info:
      state: info
      gather_subset:
        - cluster_identity_info
        - net_interface_info
        - cluster_image_info
        - cluster_node_info
        - aggregate_info
        - net_port_info
      <<: *input
    register: netapp

  - name: Print cluster details
    debug:
      msg:
        - "Name:      {{ netapp.ontap_info.cluster_identity_info.keys() | list | first }}"
        - "IP:        {{ netapp.ontap_info.net_interface_info.cluster_mgmt.address }}"
        - "Version:   {{ netapp.ontap_info.cluster_image_info['cluster1-01'].current_version }}"

  - name: Print node details
    debug:
      msg:
        - "Name:      {{ netapp.ontap_info.cluster_node_info[item].node_name }}"
    with_items:
      "{{ netapp.ontap_info.cluster_node_info }}"
    loop_control:
      label: "{{ item }}"

  - name: Print aggregate details
    debug:
      msg:
        - "Name:      {{ netapp.ontap_info.aggregate_info[item].aggregate_name }}"
        - "Node:      {{ netapp.ontap_info.aggregate_info[item].nodes.node_name }}"
        - "Size:      {{ netapp.ontap_info.aggregate_info[item].aggr_space_attributes.size_total }}"
        - "Used:      {{ netapp.ontap_info.aggregate_info[item].aggr_space_attributes.size_used }}"
    with_items:
      "{{ netapp.ontap_info.aggregate_info }}"
    when:
      netapp.ontap_info.aggregate_info[item].aggr_raid_attributes.is_root_aggregate == "false"

  - name: Print port details
    debug:
      msg:
        - "Name:      {{ netapp.ontap_info.net_port_info[item].port }}"
        - "Node:      {{ netapp.ontap_info.net_port_info[item].node }}"
        - "Speed:     {{ netapp.ontap_info.net_port_info[item].operational_speed }}"
        - "MTU:       {{ netapp.ontap_info.net_port_info[item].mtu }}"
        - "State:     {{ netapp.ontap_info.net_port_info[item].link_status }}"
        - "BC Domain: {{ netapp.ontap_info.net_port_info[item].broadcast_domain }}"
    with_items:
      "{{ netapp.ontap_info.net_port_info }}"
