#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        24_create_cifs_pri_svm.yml
# Author:       Adrian Bronder
# Date:         2020-03-20
# Description:  Create CIFS server on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_cifs_server
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_cifs_server
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create CIFS server on primary SVM
    na_ontap_cifs_server:
      state:                 present
      name:                  "{{ PRI_SVM }}"
      vserver:               "{{ PRI_SVM }}"
      domain:                "{{ PRI_AD_DOMAIN }}"
      admin_user_name:       "{{ PRI_AD_USER }}"
      admin_password:        "{{ PRI_AD_PASS }}"
      <<: *input
