#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        25_create_iscsilif_pri_svm.yml
# Author:       Adrian Bronder
#               Ronald Feist
# Date:         2020-06-16
# Description:  Create iSCSI interfaces on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_interface
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_interface
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create 1st iSCSI interface for primary SVM
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}_iscsi_01"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ PRI_SVM_ISCSI1_IP }}"
      netmask:               "{{ PRI_SVM_ISCSI_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE1 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      protocols:             iscsi
      role:                  data
      <<: *input

  - name: Create 2nd iSCSI interface for primary SVM
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}_iscsi_02"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ PRI_SVM_ISCSI2_IP }}"
      netmask:               "{{ PRI_SVM_ISCSI_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE2 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      protocols:             iscsi
      role:                  data
      <<: *input
