#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        37_create_nfsqtree_pri_svm.yml
# Author:       Adrian Bronder
# Date:         2020-03-30
# Description:  Create qtree on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_qtree
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_qtree
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create qtree on primary SVM
    na_ontap_qtree:
      state:                 present
      name:                  "nfs_01"
      vserver:               "{{ PRI_SVM }}"
      flexvol_name:          "{{ PRI_SVM }}_nfs_01"
      security_style:        unix
      <<: *input
